version: '3'
services:
  nginx:
    build: build/nginx
    ports:
      - "80:80"
    depends_on:
      - flask
    networks:
      - mynetwork 
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      mynetwork:
        aliases:
          - flask-app

networks:
  mynetwork:


