version: '3'
services:
  nginx:
    build: build/nginx
    ports:
      - "80:80"
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - mynetwork

networks:
  mynetwork:


